import Immutable from "immutable";

let questionnaire = Immutable.fromJS(
  {
    questions: [
      {
        "id":1,
        "question":"Symptoms resolved",
        "questionType":"contra",
        "answer":"yes",
        "isShown":true,
        "yes":{
          "shows":[],
          "hides":[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[2],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":2,
        "question":"Minor disabling symptoms",
        "questionType":"maybe",
        "answer":"yes",
        "isShown":false,
        "yes":{
          "shows":[3],
          "hides":[]
        },
        "no":{
          "shows":[3],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":3,
        "question":"BP > 180/110",
        "questionType":"contra",
        "answer":"yes",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[4],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":4,
        "question":"50 < Glucose < 400",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[5],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":5,
        "question":"Hemorrhage",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[6],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":6,
        "question":"Concern for neoplasm",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[7],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":7,
        "question":"Frank hypodensity in the region on symptoms",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[8],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":8,
        "question":"Are you having chest pain or pain radiating to your back",
        "questionType":"parent",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[9],
          "hides":[]
        },
        "no":{
          "shows":[12],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":9,
        "question":"Aortic dissection or Concurrent MI",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[10],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":10,
        "question":"Extracrania dissection",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[11],
          "hides":[]
        },
        "no":{
          "shows":[11],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":11,
        "question":"MI",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[12],
          "hides":[]
        },
        "no":{
          "shows":[12],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":12,
        "question":"History of bleeding issues",
        "questionType":"parent",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[13],
          "hides":[]
        },
        "no":{
          "shows":[19],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":13,
        "question":"History of iCH",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[14],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":14,
        "question":"Active bleeding",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[15],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":15,
        "question":"GI/GU bleeding in 21 days",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[16],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":16,
        "question":"CMB > 10",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[17],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":17,
        "question":"Hemorrhagic retinopath",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[18],
          "hides":[]
        },
        "no":{
          "shows":[18],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":18,
        "question":"CMB < 10",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[19],
          "hides":[]
        },
        "no":{
          "shows":[19],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":19,
        "question":"Any recent surgeries or procedures?",
        "questionType":"parent",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[20],
          "hides":[]
        },
        "no":{
          "shows":[27],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":20,
        "question":"Intracranial/intraspinal surgery in 3 months",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[21],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":21,
        "question":"Severe trauma in 3 months",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[22],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":22,
        "question":"LP within 7 days",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[23],
          "hides":[]
        },
        "no":{
          "shows":[23],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":23,
        "question":"Major surgery in 14 days",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[24],
          "hides":[]
        },
        "no":{
          "shows":[24],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":24,
        "question":"Major trauma not involving brain/spine in 14 days",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[25],
          "hides":[]
        },
        "no":{
          "shows":[25],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":25,
        "question":"Post-angio stroke",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[26],
          "hides":[]
        },
        "no":{
          "shows":[26],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":26,
        "question":"Arterial puncture in non-compressible site within 7 days",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[27],
          "hides":[]
        },
        "no":{
          "shows":[27],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":27,
        "question":"History of Cancer?",
        "questionType":"parent",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[28],
          "hides":[]
        },
        "no":{
          "shows":[32],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":28,
        "question":"Intra-axial tumor",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[29,30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[29],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":29,
        "question":"GI Malignancy",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[30,31,32,33,34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[30],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":30,
        "question":"Extraxial",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[31],
          "hides":[]
        },
        "no":{
          "shows":[31],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":31,
        "question":"Systeic malignancy",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[32],
          "hides":[]
        },
        "no":{
          "shows":[32],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":32,
        "question":"Are you taking any blood thinners or have any blood disorders?",
        "questionType":"parent",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[33],
          "hides":[]
        },
        "no":{
          "shows":[41],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":33,
        "question":"INR > 1.7",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[34,35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[34],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":34,
        "question":"PLT < 100K",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[35,36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[35],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":35,
        "question":"aPTT > 40s",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[36,37,38,39,40,41,42]
        },
        "no":{
          "shows":[36],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":36,
        "question":"PT < 15s",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[37,38,39,40,41,42]
        },
        "no":{
          "shows":[37],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":37,
        "question":"Therapeutic LMWH within 24 hours",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[38,39,40,41,42]
        },
        "no":{
          "shows":[38],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":38,
        "question":"NOAC in 48 hours",
        "questionType":"contra",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[39,40,41,42]
        },
        "no":{
          "shows":[39],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":39,
        "question":"INR <= 1.77 and PT < 15s",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[40],
          "hides":[]
        },
        "no":{
          "shows":[40],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":40,
        "question":"Sickle cell disease",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[41],
          "hides":[]
        },
        "no":{
          "shows":[41],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":41,
        "question":"Any fevers?",
        "questionType":"parent",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[41],
          "hides":[]
        },
        "no":{
          "shows":[],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      },
      {
        "id":42,
        "question":"Brain iCVA within 3 months",
        "questionType":"maybe",
        "answer":"",
        "isShown":false,
        "yes":{
          "shows":[],
          "hides":[]
        },
        "no":{
          "shows":[],
          "hides":[]
        },
        "yesPressed":"#D3D3D3",
        "noPressed":"#D3D3D3"
      }
    ],
    time: ''
  }
);

export default questionnaire;